/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'alec' at '25/06/15 20:20' with Gradle 2.4
 *
 * @author alec, @date 25/06/15 20:20
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
