import kata.minesweeper.Cell;
import kata.minesweeper.Field;
import org.junit.Test;

import static org.hamcrest.CoreMatchers.equalTo;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'alec' at '25/06/15 20:20' with Gradle 2.4
 *
 * @author alec, @date 25/06/15 20:20
 */
public class FieldTest {
    @Test
    public void dotIsNotAMine(){
        Cell cell = new Cell(".", null, null);
        assertThat(cell.isMine(),equalTo(false));

    }

    @Test public void asteriskDenotesAMine() {
        Cell cell = new Cell("*", null, null);
        assertThat(cell.isMine(), equalTo(true));
    }

    @Test
    public void aFieldOfTwoEmptyCellsDisplaysCorrectly() {
        Field field = new Field(2);
        field.addRow("..");
        assertThat(field.print(), equalTo("00%n"));

    }

    @Test
    public void aFieldOfOneMineAndOneEmptyCellDisplaysCorrectly(){
        Field field = new Field(2);
        field.addRow("*.");
        assertThat(field.print(), equalTo("*1%n"));
    }

    @Test
    public void aFieldOfTwoRowsWithOneMineDisplaysCorrectly(){
        Field field = new Field(2);
        field.addRow("*.");
        field.addRow("..");
        assertThat(field.print(), equalTo("*1%n11%n"));
    }

    @Test
    public void acceptanceTest1(){
        Field field = new Field(4);
        field.addRow("*...");
        field.addRow("....");
        field.addRow(".*..");
        field.addRow("....");
        assertThat(field.print(), equalTo("*100%n2210%n1*10%n1110%n"));
    }

    @Test
    public void acceptanceTest2(){
        Field field = new Field(5);
        field.addRow("**...");
        field.addRow(".....");
        field.addRow(".*...");
        assertThat(field.print(), equalTo("**100%n33200%n1*100%n"));
    }


}
